#ifndef APPCONFIG_H
#define APPCONFIG_H

#define APP_VERSION "0.0.0"
#define VOXEL_TERRAIN_MAX_DEPTH 14
#define VOXEL_TERRAIN_MAX_CLEAR_DEPTH 12

#define UNIFORM_CAMERA_SET_INDEX 0
#define UNIFORM_TIME_SET_INDEX 1

#endif //APPCONFIG_H
