#ifndef CONFIG_H
#define CONFIG_H

#define VERSION "0.0.0"
#define HF_ENGINE_TITLE "Hyperflow"
#define FRAMES_IN_FLIGHT 2

#if RENDERER_VULKAN
#define VULKAN_API_VERSION VK_MAKE_VERSION(1, 0, 0)
#define VULKAN_API_COLOR_FORMAT VK_FORMAT_B8G8R8A8_SRGB
#define VULKAN_API_PRESENT_MODE VK_PRESENT_MODE_MAILBOX_KHR
#define VULKAN_API_MAX_COMMANDS_PER_FRAME 8
#define VULKAN_API_MAX_TIMEOUT 2000
#define VULKAN_API_MAX_NUM_COPY_REGIONS 8
#endif

#define MAX_NUM_BUFFER_CACHE 16

#endif //CONFIG_H
