#ifndef CONFIG_H
#define CONFIG_H

#define VERSION "0.0.0"
#define HF_ENGINE_TITLE "Hyperflow"
#define FRAMES_IN_FLIGHT 2

//Uniforms
#define HF_UNIFORM_CAMERA_SET_INDEX 0

//maximum size allocated memory for a material
#define RENDERING_MAX_MATERIAL_MEMORY_BADGET 1024
//each octree consists of 4096 materials
#define RENDERING_MAX_MATERIAL_OCTREE_COUNT 1
//change this value at your own risk!
#define RENDERING_MAX_PUSH_CONSTANT_SIZE 128

#define RENDERING_MAX_UNIFORM_UPLOAD_COUNT 256
#define RENDERING_MAX_UNIFORM_UPLOAD_BUFFER_SIZE 4096 * 4
#define RENDERING_MAX_NUM_DRAW_CALLS 4096
#define RENDERING_MAX_NUM_TEXPACKS 4096
#define RENDERING_MAX_NUM_UNIFORMS 4096
#define RENDERING_MAX_NUM_DRAWPACKETS 1024
#define RENDERING_MAX_NUM_MATERIALS 1024
#define RENDERING_MAX_NUM_SHADERS 512
#define RENDERING_MAX_NUM_SHADER_SETUPS 128
#define RENDERING_MAX_NUM_RENDER_PASSES 8

//Vulkan
#define VK_MSAA_MIN_SAMPLE_SHADING 0.2f

#define VK_MAX_UNIFORM_AND_TEXTURE_UPLOADS 1024
#define VK_MAX_UNIFORM_AND_TEXTURE_BINDINGS 128
#define VK_MAX_IMAGE_BINDINGS 512
#define VK_MAX_IMAGE_BARRIERS 512
#define VK_MAX_PUSH_CONSTANT_RANGES 8

#define VULKAN_API_VERSION VK_MAKE_VERSION(1, 0, 0)
#define VULKAN_API_COLOR_FORMAT VK_FORMAT_B8G8R8A8_SRGB
#define VULKAN_API_MAX_COMMANDS_PER_FRAME 8
#define VULKAN_API_MAX_TIMEOUT 2000000000 //2seconds
#define VULKAN_API_MAX_NUM_COPY_REGIONS 8

#define MAX_NUM_BUFFER_CACHE 16
#define MAX_NUM_BOUND_TEXTUREPACKS 16

#endif //CONFIG_H
